version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: local_mariadb
    volumes: 
      - ./mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ExampleRootPass
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wpdbuser
      MYSQL_PASSWORD: wpdbuserpass

  apache1:
    depends_on:
      - db
    image: php:8.2-apache
    container_name: local_web1
    ports:
      - "80:80"
    restart: always
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/web
      WORDPRESS_DB_PREFIX: bdr
      WORDPRESS_DATABASE: wordpress1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpdbuser
      WORDPRESS_DB_PASSWORD: wpdbuserpass
    volumes:
      - type: bind
        source: ./bedrock
        target: /var/www
